apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: userapi-cert
  namespace: default
spec:
  dnsNames:
    - cmsid.crabdance.com
  secretName: userapi-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
