apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cms-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: .
    repoURL: "https://github.com/Player01Sid/cms-helm.git"
    targetRevision: master
    helm:
      releaseName: cms-app
      parameters:
      - name: "wordpress.replicas"
        value: "3"
#      - name: "namespace"
#        value: "cms-app"
#      - name: "wordpressImage.name"
#        value: "wordpress"
#      - name: "wordpressImage.tag"
#        value: "latest"
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Refresh=30s
