apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-helm-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    chart: stable/prometheus-operator
    repoURL: "https://github.com/helm/charts.git" 
    targetRevision: HEAD 
    helm:
      releaseName: prometheus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
