apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: cms
    name: wordpress-pod
spec:
  containers:
  - name: wordpress
    image: wordpress:latest
    env:
    - name: WORDPRESS_DB_HOST
      value: database
    - name: WORDPRESS_DB_USER
      valueFrom:
        configMapKeyRef:
          name: mysql-config
          key: MYSQL_USER
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_PASSWORD
    - name: WORDPRESS_DB_NAME
      valueFrom:
        configMapKeyRef:
          name: mysql-config
          key: MYSQL_DATABASE
    ports:
    - containerPort: 80
