{
 "title": "CMS",
 "description": "Namespace specific metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "cms-app CPU",
   "type": "timeseries",
   "description": "CPU used by cms-app out of total usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(sum(rate(container_cpu_usage_seconds_total{namespace=\"cms-app\"}[5m])))/(sum(rate(container_cpu_usage_seconds_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cms-app Network",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"cms-app\"}[5m]))/(1024)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"cms-app\"}[5m]))/(1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cms-app Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"cms-app\"})/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cms-app Disk read-writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"cms-app\", pod=\"mysql-0\"}[5m]))/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"cms-app\", pod=\"mysql-0\"}[5m]))/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}