{
 "title": "Namespace",
 "description": "Namespace specific metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namspace",
    "query": {
     "query": "label_values(container_memory_rss,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$namespace CPU",
   "type": "timeseries",
   "description": "CPU used by cms-app out of total usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "namespace",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])))/(sum(rate(container_cpu_usage_seconds_total[5m])))",
     "legendFormat": "CPU used by $namespace resources"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace Memory",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "repeat": "namespace",
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\"})/(1024*1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace Network",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "namespace",
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))/(1024)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))/(1024)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "cms-app Disk read-writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"cms-app\", pod=\"mysql-0\"}[5m]))/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"cms-app\", pod=\"mysql-0\"}[5m]))/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}