{
 "title": "Node",
 "description": "Metrics for Node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU usage of the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(sum(rate(node_cpu_seconds_total{cpu=\"0\",mode!=\"idle\"}[5m])))/(sum(rate(node_cpu_seconds_total{cpu=\"0\"}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100*(sum(rate(node_cpu_seconds_total{cpu=\"1\",mode!=\"idle\"}[5m])))/(sum(rate(node_cpu_seconds_total{cpu=\"1\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Data received and transmitted over network (ens3).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens3\"}[5m])/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens3\"}[5m])/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Active Memory usage by Node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_Active_bytes)/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "Disk read and writes by the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"vda\"}[5m])/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"vda\"}[5m])/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}