apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: cms
spec:
  replicas: {{ .Values.joomlaReplica }}
  selector:
    matchLabels:
      app: cms
      name: joomla-pod  
  template:
    metadata:
      name: joomla-pod
      labels:
        app: cms
        name: joomla-pod
    spec:
      containers:
      - name: joomla
        image: joomla:latest
        env:
        - name: JOOMLA_DB_HOST
          value: database
        - name: JOOMLA_DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: JOOMLA_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 80
