apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-alert-manager-configuration
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: "#prometheus-alert-webhook"
          sendResolved: true
          iconEmoji: ":bell:"
          text: "<!channel> \nSummary: Memory consumed by CMS exceeded 600MB. Value of ram used by cms-app namespace exceeded than 600MB.\nDescription: Value of ram used by cms-app namespace exceeded than 600MB.\nMessage: Resources of cms-app namespace are consuming memory more than 600. Actions required!"
  route:
    matchers:
      - name: severity
        value: critical
    receiver: slack-notifications
    repeatInterval: 1s

