apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  namespace: monitoring
  labels:
    alertmanagerConfig: my-alertmanager-config 
    release: kube-prometheus-stack
spec:
  route:
    receiver: 'webhook'

  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'https://hooks.slack.com/services/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'
