apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: my-alertmanager-config 
spec:
  route:
    groupBy: ['']
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 1h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'https://hooks.slack.com/services/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'
