apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-mysql-exporter
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus-mysql-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-mysql-exporter
    app.kubernetes.io/version: v0.15.1
    helm.sh/chart: prometheus-mysql-exporter-2.6.1
    release: kube-prometheus-stack
  name: home-exporter
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: "80"
  namespaceSelector:
    matchNames:
    - cms-app
  selector:
    matchLabels:
      app: home
