prometheus:
  enabled: true
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: "10s"
    scrapeTimeout: "20s"
    evaluationInterval: "10s"


alertmanager:
  config:
    global:
      slack_api_url: https://hooks.slack.com/services/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
  alertmanagerSpec:
    forceEnableClusterMode: true
    alertmanagerConfigNamespaceSelector:
    alertmanagerConfigSelector:
    alertmanagerConfigMatcherStrategy:
      type: None

