apiVersion: argoporj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  description: project test
  sourceRepos:
    - "*"
  destination:
    - server: https://kubernetes.default.svc
      namespace: "test"
  clusterResourceWhitelist:
    - group: ""
      kind "Namespace"
